name: Daily Kaggle Crypto Download

on:
  schedule:
    - cron: '0 7 * * *'  # 2 AM EST = 7 AM UTC
  workflow_dispatch:

permissions:
    contents: write


jobs:
  download:
    runs-on: ubuntu-latest

    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Create Kaggle config
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run download script
        run: python scripts/download_kaggle_dataset.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git commit -m "🔄 Daily data update"
          git push
        continue-on-error: true
